version: '3.0'

services:
  node:
    container_name: node
    image: node:latest
    build: .
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    working_dir: /app
    command: bash -c "npm install && node httpServer.js"
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - MONGODB_URL="mongodb://host.docker.internal"
      - MONGODB_PORT=27017
      - MONGODB_DBATABASE="testDB"
      - JWT_SECRET="hocuNoviFont"
      - HTTP_SERVER_HOST:"localhost"
      - HTTP_SERVER_PORT=5000
      - WS_SERVER_HOST="localhost"
      - WS_SERVER_PORT=5001
    depends_on:
      - mongo
    networks:
      - nodeNetwork
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - c:/mongo/data:/data/db
    networks:
      - nodeNetwork
      
networks:
  nodeNetwork:
    driver: bridge
