version: '3.0'

services:
  node:
    container_name: node
    #image: antasmes/nxt-server:dev
    build: .
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    working_dir: /app
    command: bash -c "npm install && npx ts-node httpServer.ts"
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - MONGODB_URL=mongodb://mongo
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=testDB
      - JWT_SECRET=hocuNoviFont
      - HTTP_SERVER_HOST=localhost
      - HTTP_SERVER_PORT=5000
      - WS_SERVER_HOST=localhost
      - WS_SERVER_PORT=5001
      - PYTHON_SERVER_HOST=python
      - PYTHON_SERVER_PORT=5003
      - B_SALT=8
      - EMAIL_AUTH_USER=akitasevski113@gmail.com
      - EMAIL_AUTH_PASS=skofigbukcdratsf
    depends_on:
      - mongo
    networks:
      - nodeNetwork
  python:
    container_name: python
    image: antasmes/python-server:dev
    volumes:
      - ../pysrc:/usr/app/
    working_dir: /usr/app
    command: bash -c "pip install numpy python-socketio asyncio flask[async] opencv-python-headless matplotlib imageio requests && python main.py"
    ports:
      - "5003:5003"
    networks:
      - nodeNetwork
    depends_on:
      - node
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - c:/mongo/data:/data/db
    networks:
      - nodeNetwork

networks:
  nodeNetwork:
    driver: bridge