name: Docker Build CI

on:
  push:
    branches:
      - main
      - dev
      
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to docker hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_ANTASMES }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD_ANTASMES }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: |
        docker build ./src -t antasmes/nxt-server:latest
        docker save -o tmp_mage.tar antasmes/nxt-server:latest
      continue-on-error: true
    - name: Upload image artifact
      uses: actions/upload-artifact@v3
      with:
        name: image
        path: tmp_image.tar
  publish-main:
      if: github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      needs: [build, login]
      steps:
      - name: Download image artifact
        uses: actions/download-artifact@v3
        with:
          name: image
      - name: Load image
        run: docker load -i tmp_image.tar
      - name: Docker push
        run: |
          docker push antasmes/nxt-server:latest
  publish-dev:
      if: github.ref == 'refs/heads/dev'
      runs-on: ubuntu-latest
      needs: [build, login]
      steps:
      - name: Download image artifact
        uses: actions/download-artifact@v3
        with:
          name: image
      - name: Load image
        run: docker load -i tmp_image.tar
      - name: Re-tag image
        run: |
          docker tag antasmes/nxt-server:latest antasmes/nxt-server:dev
      - name: Docker push
        run: |
          docker push antasmes/nxt-server:dev  
        
    
    
